### ISSUE TITLE
关于生成卡死现象

### ISSUE THREAD

**Issue by evilc0deooo** [TheKingOfDuck/MatryoshkaDollTool#1]
系统是 Windows 7 ，测试该软件时发现提示未响应，多次卡死现象，捆绑的文件一大小50KB，捆绑的文件二大小30MB以内（测试2MB同样出现卡死），表哥该问题怎么解决？

**Comment by TheKingOfDuck** [comment]
@ppbibo 有莫得装vs2019之类的啊
